# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: holo_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='holo_msg.proto',
  package='holo',
  serialized_pb=_b('\n\x0eholo_msg.proto\x12\x04holo\"\x85\x05\n\x0fStandardCommand\x12+\n\x03\x63md\x18\x01 \x02(\x0e\x32\x1e.holo.StandardCommand.CmdTypes\x12#\n\nimage_meta\x18\x02 \x03(\x0b\x32\x0f.holo.ImageMeta\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x12\n\nwavelength\x18\x04 \x01(\x02\x12<\n\talgorithm\x18\x05 \x01(\x0e\x32$.holo.StandardCommand.AlgorithmTypes:\x03GLS\x12\x18\n\x0c\x65xtraZlevels\x18\x06 \x03(\x01\x42\x02\x10\x01\x12\x1c\n\x14\x63\x61libration_circle_x\x18\x07 \x01(\x02\x12\x1c\n\x14\x63\x61libration_circle_y\x18\x08 \x01(\x02\x12\x1b\n\x13\x63\x61libration_Z_level\x18\t \x01(\x02\x12\x19\n\x11\x63orrection_factor\x18\n \x01(\x02\x12\x17\n\x0fobjectiveZlevel\x18\x0b \x01(\x02\"\xfa\x01\n\x08\x43mdTypes\x12\n\n\x06STATUS\x10\x00\x12\x0c\n\x08GENERATE\x10\x01\x12\x08\n\x04PLAY\x10\x02\x12\x11\n\rCALIBRATE_RUN\x10\x03\x12\x18\n\x14\x43\x41LIBRATE_BACKGROUND\x10\x04\x12\x14\n\x10\x43\x41LIBRATE_CIRCLE\x10\x05\x12\x0f\n\x0b\x43\x41LIBRATE_Z\x10\x06\x12\x13\n\x0f\x43\x41LIBRATE_Z_RUN\x10\x07\x12\x1f\n\x1b\x43\x41LIBRATE_CORRECTION_FACTOR\x10\x08\x12\x14\n\x10\x43\x41LIBRATE_TIMING\x10\t\x12\x15\n\x11\x43\x41LIBRATE_RELEASE\x10\n\x12\x13\n\x0f\x43\x41LIBRATE_Z_OBJ\x10\x0b\"\x19\n\x0e\x41lgorithmTypes\x12\x07\n\x03GLS\x10\x00\"\xd1\x02\n\rStandardReply\x12-\n\x05reply\x18\x01 \x02(\x0e\x32\x1e.holo.StandardReply.ReplyTypes\x12#\n\nimage_meta\x18\x02 \x03(\x0b\x32\x0f.holo.ImageMeta\x12-\n\x05\x65rror\x18\x03 \x01(\x0e\x32\x1e.holo.StandardReply.ErrorTypes\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12$\n\x1c\x63\x61librated_correction_factor\x18\x05 \x01(\x02\"\x1f\n\nReplyTypes\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\"_\n\nErrorTypes\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08HARDWARE\x10\x01\x12\x0c\n\x08SOFTWARE\x10\x02\x12\x0f\n\x0b\x42\x41\x44_REQUEST\x10\x03\x12\x17\n\x13NOT_YET_IMPLEMENTED\x10\x04\"@\n\tImageMeta\x12\x0e\n\x06Zlevel\x18\x01 \x02(\x01\x12\x11\n\tframe_num\x18\x02 \x02(\x05\x12\x10\n\x08\x64uration\x18\x04 \x02(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_STANDARDCOMMAND_CMDTYPES = _descriptor.EnumDescriptor(
  name='CmdTypes',
  full_name='holo.StandardCommand.CmdTypes',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GENERATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALIBRATE_RUN', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALIBRATE_BACKGROUND', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALIBRATE_CIRCLE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALIBRATE_Z', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALIBRATE_Z_RUN', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALIBRATE_CORRECTION_FACTOR', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALIBRATE_TIMING', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALIBRATE_RELEASE', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALIBRATE_Z_OBJ', index=11, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=393,
  serialized_end=643,
)
_sym_db.RegisterEnumDescriptor(_STANDARDCOMMAND_CMDTYPES)

_STANDARDCOMMAND_ALGORITHMTYPES = _descriptor.EnumDescriptor(
  name='AlgorithmTypes',
  full_name='holo.StandardCommand.AlgorithmTypes',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GLS', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=645,
  serialized_end=670,
)
_sym_db.RegisterEnumDescriptor(_STANDARDCOMMAND_ALGORITHMTYPES)

_STANDARDREPLY_REPLYTYPES = _descriptor.EnumDescriptor(
  name='ReplyTypes',
  full_name='holo.StandardReply.ReplyTypes',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=882,
  serialized_end=913,
)
_sym_db.RegisterEnumDescriptor(_STANDARDREPLY_REPLYTYPES)

_STANDARDREPLY_ERRORTYPES = _descriptor.EnumDescriptor(
  name='ErrorTypes',
  full_name='holo.StandardReply.ErrorTypes',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HARDWARE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTWARE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAD_REQUEST', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_YET_IMPLEMENTED', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=915,
  serialized_end=1010,
)
_sym_db.RegisterEnumDescriptor(_STANDARDREPLY_ERRORTYPES)


_STANDARDCOMMAND = _descriptor.Descriptor(
  name='StandardCommand',
  full_name='holo.StandardCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='holo.StandardCommand.cmd', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_meta', full_name='holo.StandardCommand.image_meta', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='holo.StandardCommand.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wavelength', full_name='holo.StandardCommand.wavelength', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='holo.StandardCommand.algorithm', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extraZlevels', full_name='holo.StandardCommand.extraZlevels', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='calibration_circle_x', full_name='holo.StandardCommand.calibration_circle_x', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='calibration_circle_y', full_name='holo.StandardCommand.calibration_circle_y', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='calibration_Z_level', full_name='holo.StandardCommand.calibration_Z_level', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='correction_factor', full_name='holo.StandardCommand.correction_factor', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='objectiveZlevel', full_name='holo.StandardCommand.objectiveZlevel', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STANDARDCOMMAND_CMDTYPES,
    _STANDARDCOMMAND_ALGORITHMTYPES,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=670,
)


_STANDARDREPLY = _descriptor.Descriptor(
  name='StandardReply',
  full_name='holo.StandardReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='holo.StandardReply.reply', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_meta', full_name='holo.StandardReply.image_meta', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='holo.StandardReply.error', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='holo.StandardReply.error_message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='calibrated_correction_factor', full_name='holo.StandardReply.calibrated_correction_factor', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STANDARDREPLY_REPLYTYPES,
    _STANDARDREPLY_ERRORTYPES,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=673,
  serialized_end=1010,
)


_IMAGEMETA = _descriptor.Descriptor(
  name='ImageMeta',
  full_name='holo.ImageMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Zlevel', full_name='holo.ImageMeta.Zlevel', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame_num', full_name='holo.ImageMeta.frame_num', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='holo.ImageMeta.duration', index=2,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1012,
  serialized_end=1076,
)

_STANDARDCOMMAND.fields_by_name['cmd'].enum_type = _STANDARDCOMMAND_CMDTYPES
_STANDARDCOMMAND.fields_by_name['image_meta'].message_type = _IMAGEMETA
_STANDARDCOMMAND.fields_by_name['algorithm'].enum_type = _STANDARDCOMMAND_ALGORITHMTYPES
_STANDARDCOMMAND_CMDTYPES.containing_type = _STANDARDCOMMAND
_STANDARDCOMMAND_ALGORITHMTYPES.containing_type = _STANDARDCOMMAND
_STANDARDREPLY.fields_by_name['reply'].enum_type = _STANDARDREPLY_REPLYTYPES
_STANDARDREPLY.fields_by_name['image_meta'].message_type = _IMAGEMETA
_STANDARDREPLY.fields_by_name['error'].enum_type = _STANDARDREPLY_ERRORTYPES
_STANDARDREPLY_REPLYTYPES.containing_type = _STANDARDREPLY
_STANDARDREPLY_ERRORTYPES.containing_type = _STANDARDREPLY
DESCRIPTOR.message_types_by_name['StandardCommand'] = _STANDARDCOMMAND
DESCRIPTOR.message_types_by_name['StandardReply'] = _STANDARDREPLY
DESCRIPTOR.message_types_by_name['ImageMeta'] = _IMAGEMETA

StandardCommand = _reflection.GeneratedProtocolMessageType('StandardCommand', (_message.Message,), dict(
  DESCRIPTOR = _STANDARDCOMMAND,
  __module__ = 'holo_msg_pb2'
  # @@protoc_insertion_point(class_scope:holo.StandardCommand)
  ))
_sym_db.RegisterMessage(StandardCommand)

StandardReply = _reflection.GeneratedProtocolMessageType('StandardReply', (_message.Message,), dict(
  DESCRIPTOR = _STANDARDREPLY,
  __module__ = 'holo_msg_pb2'
  # @@protoc_insertion_point(class_scope:holo.StandardReply)
  ))
_sym_db.RegisterMessage(StandardReply)

ImageMeta = _reflection.GeneratedProtocolMessageType('ImageMeta', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEMETA,
  __module__ = 'holo_msg_pb2'
  # @@protoc_insertion_point(class_scope:holo.ImageMeta)
  ))
_sym_db.RegisterMessage(ImageMeta)


_STANDARDCOMMAND.fields_by_name['extraZlevels'].has_options = True
_STANDARDCOMMAND.fields_by_name['extraZlevels']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
